name: Reusable workflow

on:
  workflow_call:
    outputs:
      env:
        description: "en"
        value:  ${{ fromJSON('{develop:"dev",qa:"qa", master:"prod"}')[jobs.reusable_job.outputs.output1] }}
        

jobs:
  reusable_job:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ env.git_short_ref }}

    steps:
      - name: "Set github short ref"
        id: vars
        run: |
          echo "GITHUB_REF=${GITHUB_REF}"
          echo "git_short_ref=$(echo ${GITHUB_REF#refs/*/})" >> $GITHUB_ENV