name: 'Build and Deploy to dev'

on:
  push:
    branches:
      - develop
      - master
      - qa

jobs:
  deploy-to-env:
    if: [[ "${{github.base_ref}}" == "develop" || "${{github.ref}}" == "refs/heads/develop" ]]
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
      env: dev
    if: [[ "${{github.base_ref}}" == "master" || "${{github.ref}}" == "refs/heads/master" ]]
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
        env: prod
    if: [[ "${{github.base_ref}}" == "qa" || "${{github.ref}}" == "refs/heads/qa" ]]
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
        env: qa
