name: 'Build and Deploy to dev'

on:
  push:
    branches:
      - develop
      - master
      - qa

jobs:
  deploy-to-env:
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
        if: [[ "${{github.base_ref}}" == "develop" || "${{github.ref}}" == "refs/heads/develop" ]]
          env: dev
        if: [[ "${{github.base_ref}}" == "master" || "${{github.ref}}" == "refs/heads/master" ]]
          env: prod
        if: [[ "${{github.base_ref}}" == "qa" || "${{github.ref}}" == "refs/heads/qa" ]]
          env: qa
