name: 'Build and Deploy to dev'

on:
  push:
    branches:
      - develop
      - master
      - qa

jobs:
  call_reuable_code:
    uses: ./.github/workflows/git_env.yml
  deploy-to-env:
    name: "deploy to environment"
    uses: ./.github/workflows/test.yml
    needs: call_reuable_code
    secrets: inherit
    with:
      env: ${{ needs.call_reuable_code.outputs.git_short_ref }}
