name: Reusable workflow

on:
  workflow_call:
    outputs:
      git_short_ref:
        description: "git_short_ref"
        value: ${{ jobs.reusable_job.outputs.output1 }}

jobs:
  reusable_job:
    runs-on: ubuntu-latest
    environment: prod
    outputs:
      output1: ${{ steps.vars.outputs.git_short_ref }}
    steps:
      - name: "Set github short ref"
        id: vars
        run: |
          echo "GITHUB_REF=${GITHUB_REF}"
          echo "::set-output name=git_short_ref::${GITHUB_REF#refs/*/}"
      - name: cehckout
        uses: actions/checkout@v2
      - name: "install node 14"
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: "install packages"
        run: |
          npm install -g npm@7
          npm install
