name: "test"

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - run: npm install
      - run: echo "${{ inputs.env }}"
