name: var_per_env
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - develop
      - master
  workflow_dispatch:

jobs:
  set_up_env_var:
    runs-on: ubuntu-latest
    steps:
      - name: check git short ref
        run: |
          echo "${GITHUB_BRANCH##*/}"
      - name: Set env to staging
        if: steps.vars.outputs.git_short_ref == 'develop' && github.event_name == 'push'
        run: |
          echo "::set-env name=ENVIRONMENT::dev"
          echo "${{ toJSON(secrets) }}"
      - name: Set env to production
        if: steps.vars.outputs.git_short_ref == 'develop' && github.event_name == 'workflow_dispatch'
        run: |
          echo "::set-env name=ENVIRONMENT::qa"
          echo "${{ toJSON(secrets) }}"
      - name: Set env to production
        if: steps.vars.outputs.git_short_ref == 'develop' && github.event_name == 'workflow_dispatch'
        run: |
          echo "::set-env name=ENVIRONMENT::prod"
          echo "${{ toJSON(secrets) }}"
